name: Release
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  publish:
    name: Publish release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --relesae --target ${{ matrix.target }}
      
      - name: Make asset
        shell: bash
        run: |
          name="nomi-${{ matrix.target }}"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "target/${{ matrix.target }}/release/client.exe" "$name.exe"
            echo "ASSET=$name.exe" >> $GITHUB_ENV
          else
            mv "target/${{ matrix.target }}/release/client" "$name"
            echo "ASSET=$name" >> $GITHUB_ENV
          fi

      - name:
        uses: softprops/actions-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}
