name: Test build
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review, review_requested]

jobs:
  testbuild:
    name: Test build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build project
        uses: actions-rs/cargo@v1.0.1
        with:
          use-cross: true
          command: build
          args: --verbose --release --target ${{ matrix.target }}
